# Copyright (c) 2023-2026, Songlin Yang, Yu Zhang, Zhiyuan Li
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
# For a list of all contributors, visit:
#   https://github.com/fla-org/flash-linear-attention/graphs/contributors

import importlib

# Names resolve to their submodule on first access, so importing one kernel family does not pay for the
# whole library: several families import torch.compile / DTensor at module level, which costs seconds.
_SUBMODULES = {
    'chunk_abc': 'abc',
    'chunk_comba': 'comba',
    'chunk_delta_rule': 'delta_rule',
    'chunk_dplr_delta_rule': 'generalized_delta_rule',
    'chunk_gated_delta_rule': 'gated_delta_rule',
    'chunk_gdn': 'gated_delta_rule',
    'chunk_gla': 'gla',
    'chunk_gsa': 'gsa',
    'chunk_iplr_delta_rule': 'generalized_delta_rule',
    'chunk_kda': 'kda',
    'chunk_lightning_attn': 'lightning_attn',
    'chunk_linear_attn': 'linear_attn',
    'chunk_log_linear_attn': 'log_linear_attn',
    'chunk_mesa_net': 'mesa_net',
    'chunk_retention': 'retention',
    'chunk_rwkv6': 'rwkv6',
    'chunk_rwkv7': 'rwkv7',
    'chunk_simple_gla': 'simple_gla',
    'fused_attnres': 'attnres',
    'fused_chunk_based': 'based',
    'fused_chunk_delta_rule': 'delta_rule',
    'fused_chunk_gla': 'gla',
    'fused_chunk_linear_attn': 'linear_attn',
    'fused_chunk_retention': 'retention',
    'fused_chunk_simple_gla': 'simple_gla',
    'fused_recurrent_comba': 'comba',
    'fused_recurrent_delta_rule': 'delta_rule',
    'fused_recurrent_dplr_delta_rule': 'generalized_delta_rule',
    'fused_recurrent_gated_delta_rule': 'gated_delta_rule',
    'fused_recurrent_gdn': 'gated_delta_rule',
    'fused_recurrent_gla': 'gla',
    'fused_recurrent_gsa': 'gsa',
    'fused_recurrent_hgrn': 'hgrn',
    'fused_recurrent_iplr_delta_rule': 'generalized_delta_rule',
    'fused_recurrent_kda': 'kda',
    'fused_recurrent_lightning_attn': 'lightning_attn',
    'fused_recurrent_linear_attn': 'linear_attn',
    'fused_recurrent_retention': 'retention',
    'fused_recurrent_rwkv6': 'rwkv6',
    'fused_recurrent_rwkv7': 'rwkv7',
    'fused_recurrent_simple_gla': 'simple_gla',
    'parallel_attn': 'attn',
    'parallel_based': 'based',
    'parallel_forgetting_attn': 'forgetting_attn',
    'parallel_nsa': 'nsa',
    'parallel_parallax': 'parallax',
    'parallel_path_attn': 'path_attn',
    'parallel_retention': 'retention',
    'parallel_simple_gla': 'simple_gla',
    'parallel_wall_attn': 'wall_attn',
    'parallel_wall_attn_decode': 'wall_attn',
}

__all__ = [
    'chunk_abc',
    'chunk_comba',
    'chunk_delta_rule',
    'chunk_dplr_delta_rule',
    'chunk_gated_delta_rule',
    'chunk_gdn',
    'chunk_gla',
    'chunk_gsa',
    'chunk_iplr_delta_rule',
    'chunk_kda',
    'chunk_lightning_attn',
    'chunk_linear_attn',
    'chunk_log_linear_attn',
    'chunk_mesa_net',
    'chunk_retention',
    'chunk_rwkv6',
    'chunk_rwkv7',
    'chunk_simple_gla',
    'fused_attnres',
    'fused_chunk_based',
    'fused_chunk_delta_rule',
    'fused_chunk_gla',
    'fused_chunk_linear_attn',
    'fused_chunk_retention',
    'fused_chunk_simple_gla',
    'fused_recurrent_comba',
    'fused_recurrent_delta_rule',
    'fused_recurrent_dplr_delta_rule',
    'fused_recurrent_gated_delta_rule',
    'fused_recurrent_gdn',
    'fused_recurrent_gla',
    'fused_recurrent_gsa',
    'fused_recurrent_hgrn',
    'fused_recurrent_iplr_delta_rule',
    'fused_recurrent_kda',
    'fused_recurrent_lightning_attn',
    'fused_recurrent_linear_attn',
    'fused_recurrent_retention',
    'fused_recurrent_rwkv6',
    'fused_recurrent_rwkv7',
    'fused_recurrent_simple_gla',
    'parallel_attn',
    'parallel_based',
    'parallel_forgetting_attn',
    'parallel_nsa',
    'parallel_parallax',
    'parallel_path_attn',
    'parallel_retention',
    'parallel_simple_gla',
    'parallel_wall_attn',
    'parallel_wall_attn_decode',
]


def __getattr__(name: str):
    submodule = _SUBMODULES.get(name)
    if submodule is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    return getattr(importlib.import_module(f"{__name__}.{submodule}"), name)
